#!/usr/bin/env bash
# Update package list and install nginx
apt-get update

# Install Nginx
apt-get install -y nginx

# Remove the default Nginx configuration file
rm /etc/nginx/sites-enabled/default

# Create a new Nginx configuration file
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}" > /etc/nginx/sites-available/default

# Create a new index.html file
echo "Hello World!" > /var/www/html/index.html

# Start Nginx (without using systemctl)
service nginx start
