#!/usr/bin/env bash
# Update the package lists for upgrades and new package installations
sudo apt-get update
sudo apt-get install -y nginx
sudo rm /etc/nginx/sites-enabled/default
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx start
