#!/usr/bin/env bash
# Script to print TCP and UDP ports
echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
netstat -tulnp | awk 'NR>2 {print $1,$4,$5,$6}' | while read proto local foreign state; do
    pid=$(echo $state | cut -d'/' -f1)
    program=$(echo $state | cut -d'/' -f2)
    echo "$proto        $local        $foreign        $state        $pid/$program"
done

echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"
netstat -lx | awk 'NR>2 {print $1,$2,$3,$4,$5,$6}' | while read proto refcnt flags type state inode; do
    pid=$(echo $state | cut -d'/' -f1)
    program=$(echo $state | cut -d'/' -f2)
    echo "$proto  $refcnt  $flags  $type  $state  $inode  $pid/$program"
done
