#!/usr/bin/env bash
# Function to handle signals
handle_signal() {
  case $1 in
    SIGINT)
      echo "Y U no love me?!"
      ;;
    SIGTERM)
      echo "I hate the kill command"
      rm /var/run/myscript.pid
      exit 0
      ;;
    SIGQUIT)
      rm /var/run/myscript.pid
      exit 0
      ;;
  esac
}
trap 'handle_signal SIGINT' SIGINT
trap 'handle_signal SIGTERM' SIGTERM
trap 'handle_signal SIGQUIT' SIGQUIT
echo $$ > /var/run/myscript.pid
while true
do
  echo "To infinity and beyond"
  sleep 2
done
