#!/usr/bin/env bash
# Function to handle SIGTERM signal
handle_sigterm() {
  echo "I am invincible!!!"
}

# Set up SIGTERM signal handler
trap 'handle_sigterm' SIGTERM

# Infinite loop
while true
do
  echo "To infinity and beyond"
  sleep 2
done
