#!/usr/bin/env bash
# Script that displays "bad luck" "good luck" and "Best School" in its iterations
count=0
while [ "$count" -lt 10 ]; do
	if [ "$count" -eq 3 ]; then
		echo "bad luck"
	elif [ "$count" -eq 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((count++))
done
