#!/usr/bin/env bash
# Script to display numbers from 1 to 20
count=1
while [ "$count" -le 20 ]; do
	if [ "$count" -eq 5 ]; then
		echo "bad luck from China"
	elif [ "$count" -eq 10 ]; then
		echo "bad luck from Japan"
	elif [ "$count" -eq 18 ]; then
		echo "bad luck from Italy"
	else
		echo "$count"
	fi
	((count++))
done
