#!/usr/bin/env bash
# Script to display numbers from 1 to 20
count=1
while [ "$count" -le 20 ]; do
	case "$count" in
		5) echo "bad luck from China"
			;;
		10) echo "bad luck from Japan"
			;;
		18) echo "bad luck from Italy"
			;;
		*) echo "$count"
			;;
	esac
		((count++))
done
