#!/usr/bin/env bash

# Function to display subdomain info
display_info() {
    local record_info
    local record_type
    local destination
    local domain=$1
    local subdomain=$2
    record_info=$(dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:')
    record_type=$(echo "$record_info" | awk '{print $4}')
    destination=$(echo "$record_info" | awk '{print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Check if domain argument is provided
if [ -z "$1" ]; then
    echo "Please provide a domain name."
    exit 1
fi

# Check if subdomain argument is provided
if [ -z "$2" ]; then
    # Display info for default subdomains
    for subdomain in www lb-01 web-01 web-02; do
        display_info "$1" $subdomain
    done
else
    # Display info for specified subdomain
    display_info "$1" "$2"
fi

